stages:
  prepare:
    cmd: python src/prepare.py data/mnist_train.csv data/mnist_test.csv
    deps:
    - data/mnist_test.csv
    - data/mnist_train.csv
    - src/prepare.py
    outs:
    - data/prepared
  train:
    cmd: python src/train.py data/prepared data/metrics/master_acc.json data/metrics/master_loss.json
    deps:
    - data/prepared
    - src/train.py
    params:
    - train.random_state
    - train.split_val
    - train.max_iter
    - train.learning_rate_init
    - train.batch_size
    metrics:
    - data/metrics/master_acc.json:
        cache: false
    plots:
    - data/metrics/master_loss.json:
        cache: false
